from django.urls import path
from .views import (
    add_reply,
    admin_activity_log,
    admin_insights,
    admin_reports,
    admin_trends,
    admin_topics,
    approve_class_join_request,
    approve_faculty,
    approve_topic_request,
    class_conversations,
    class_detail,
    class_join_requests,
    class_resources,
    class_students,
    classes,
    create_class,
    create_class_discussion,
    create_class_discussion_reply,
    create_topic,
    delete_class_discussion,
    delete_class_discussion_reply,
    delete_notification,
    delete_reply,
    delete_topic_request,
    delete_user,
    faculty_requests,
    leave_class,
    login,
    mark_all_notifications_read,
    mark_messages_read,
    mark_notification_read,
    message_conversations,
    message_thread,
    moderate_reported_content,
    notifications,
    pending_topic_requests,
    posts,
    reject_class_join_request,
    reject_topic_request,
    remove_student_from_class,
    report_content,
    request_more_topic_info,
    resolve_report,
    send_message_db,
    signup,
    submit_class_join_request,
    submit_topic_request,
    toggle_pin_class_discussion,
    toggle_topic_status,
    toggle_user_status,
    topic_request_timelines,
    topics,
    upload_class_resource,
    update_reply,
    update_user_profile,
    upvote_class_discussion,
    upvote_class_discussion_reply,
    upvote_reply,
    upvote_topic,
    user_engagement_summary,
    user_replies,
    user_topics,
    users,
)

urlpatterns = [

    # topics
    path('topics/', topics),
    path('posts/<int:topic_id>/', posts),
    path('user-topics/<int:user_id>/', user_topics),
    path('user-replies/<int:user_id>/', user_replies),
    path('user-engagement-summary/<int:user_id>/', user_engagement_summary),
    path('classes/', classes),
    path('classes/<int:class_id>/', class_detail),
    path('class-join-requests/', class_join_requests),
    path('class-students/<int:class_id>/', class_students),
    path('class-conversations/<int:class_id>/', class_conversations),
    path('class-resources/<int:class_id>/', class_resources),

    # auth
    path('login/', login),
    path('signup/', signup),

    # topic
    path('create-topic/', create_topic),
    path('submit-topic-request/', submit_topic_request),
    path('create-class/', create_class),
    path('submit-class-join-request/', submit_class_join_request),
    path('approve-class-join-request/', approve_class_join_request),
    path('reject-class-join-request/', reject_class_join_request),
    path('leave-class/', leave_class),
    path('remove-student-from-class/', remove_student_from_class),
    path('create-class-discussion/', create_class_discussion),
    path('create-class-discussion-reply/', create_class_discussion_reply),
    path('delete-class-discussion/', delete_class_discussion),
    path('delete-class-discussion-reply/', delete_class_discussion_reply),
    path('upvote-class-discussion/', upvote_class_discussion),
    path('upvote-class-discussion-reply/', upvote_class_discussion_reply),
    path('toggle-pin-class-discussion/', toggle_pin_class_discussion),
    path('upload-class-resource/', upload_class_resource),
    path('pending-topic-requests/', pending_topic_requests),
    path('admin-topics/', admin_topics),
    path('admin-reports/', admin_reports),
    path('admin-activity-log/', admin_activity_log),
    path('admin-insights/', admin_insights),
    path('admin-trends/', admin_trends),
    path('approve-topic-request/', approve_topic_request),
    path('toggle-topic-status/', toggle_topic_status),
    path('reject-topic-request/', reject_topic_request),
    path('delete-topic-request/', delete_topic_request),
    path('resolve-report/', resolve_report),
    path('notifications/<int:user_id>/', notifications),
    path('mark-notification-read/', mark_notification_read),
    path('mark-all-notifications-read/', mark_all_notifications_read),
    path('delete-notification/', delete_notification),

    # replies
    path('add-reply/', add_reply),
    path('delete-reply/', delete_reply),
    path('update-reply/', update_reply),
    path('upvote-topic/', upvote_topic),
    path('upvote-reply/', upvote_reply),
    path('report-content/', report_content),

    # users
    path('users/', users),
    path('update-user-profile/', update_user_profile),
    path('messages/conversations/<int:user_id>/', message_conversations),
    path('messages/thread/<int:user_id>/<int:other_user_id>/', message_thread),
    path('messages/send/', send_message_db),
    path('messages/mark-read/', mark_messages_read),
    path('toggle-user/', toggle_user_status),
    path('delete-user/', delete_user),
    path('faculty_requests/', faculty_requests),
    path('approve_faculty/', approve_faculty),

]
