CREATE TABLE IF NOT EXISTS CLASSROOM (
    CLASS_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLASS_CODE VARCHAR(100) NOT NULL,
    SUBJECT_NAME VARCHAR(255) NOT NULL,
    TIMINGS VARCHAR(255) NOT NULL,
    CLASS_AREA VARCHAR(255) NOT NULL,
    DEPARTMENT VARCHAR(100) DEFAULT 'General',
    INSTRUCTOR_ID INT NOT NULL,
    SEMESTER VARCHAR(100) DEFAULT 'Spring 2026',
    DESCRIPTION TEXT NULL,
    DAYS VARCHAR(255) DEFAULT 'To Be Announced',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (INSTRUCTOR_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE IF NOT EXISTS CLASS_ENROLLMENT (
    ENROLLMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLASS_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'pending',
    REQUESTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REVIEWED_AT TIMESTAMP NULL,
    FOREIGN KEY (CLASS_ID) REFERENCES CLASSROOM(CLASS_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES USER(USER_ID),
    UNIQUE KEY unique_class_student (CLASS_ID, STUDENT_ID)
);

CREATE TABLE IF NOT EXISTS CLASS_DISCUSSION (
    DISCUSSION_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLASS_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATED_BY INT NOT NULL,
    IS_PINNED TINYINT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CLASS_ID) REFERENCES CLASSROOM(CLASS_ID),
    FOREIGN KEY (CREATED_BY) REFERENCES USER(USER_ID)
);

CREATE TABLE IF NOT EXISTS CLASS_DISCUSSION_REPLY (
    REPLY_ID INT AUTO_INCREMENT PRIMARY KEY,
    DISCUSSION_ID INT NOT NULL,
    CLASS_ID INT NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATED_BY INT NOT NULL,
    PARENT_REPLY_ID INT NULL,
    IS_DELETED TINYINT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DISCUSSION_ID) REFERENCES CLASS_DISCUSSION(DISCUSSION_ID),
    FOREIGN KEY (CLASS_ID) REFERENCES CLASSROOM(CLASS_ID),
    FOREIGN KEY (CREATED_BY) REFERENCES USER(USER_ID),
    FOREIGN KEY (PARENT_REPLY_ID) REFERENCES CLASS_DISCUSSION_REPLY(REPLY_ID)
);

CREATE TABLE IF NOT EXISTS CLASS_DISCUSSION_VOTE (
    VOTE_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    DISCUSSION_ID INT NULL,
    REPLY_ID INT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (DISCUSSION_ID) REFERENCES CLASS_DISCUSSION(DISCUSSION_ID),
    FOREIGN KEY (REPLY_ID) REFERENCES CLASS_DISCUSSION_REPLY(REPLY_ID),
    UNIQUE KEY unique_discussion_vote (USER_ID, DISCUSSION_ID),
    UNIQUE KEY unique_discussion_reply_vote (USER_ID, REPLY_ID)
);

CREATE INDEX idx_class_enrollment_status ON CLASS_ENROLLMENT(CLASS_ID, STATUS);
CREATE INDEX idx_class_discussion_class ON CLASS_DISCUSSION(CLASS_ID, CREATED_AT);
CREATE INDEX idx_class_discussion_reply_discussion ON CLASS_DISCUSSION_REPLY(DISCUSSION_ID, CREATED_AT);
