ALTER TABLE UPVOTE
ADD COLUMN TOPIC_ID INT NULL AFTER POST_ID;

ALTER TABLE UPVOTE
ADD CONSTRAINT fk_upvote_topic
FOREIGN KEY (TOPIC_ID) REFERENCES TOPIC(TOPIC_ID);

ALTER TABLE UPVOTE
ADD UNIQUE KEY unique_topic_vote (USER_ID, TOPIC_ID);
