CREATE DATABASE IF NOT EXISTS uniconnectdb;
USE uniconnectdb;

SET SQL_SAFE_UPDATES = 0;

-- Core user profile columns required by the current app
ALTER TABLE USER ADD COLUMN IF NOT EXISTS IS_ACTIVE BOOLEAN DEFAULT TRUE;
ALTER TABLE USER ADD COLUMN IF NOT EXISTS ROLE VARCHAR(20) DEFAULT 'student';
ALTER TABLE USER ADD COLUMN IF NOT EXISTS STATUS VARCHAR(20) DEFAULT 'approved';
ALTER TABLE USER ADD COLUMN IF NOT EXISTS BIO TEXT NULL;
ALTER TABLE USER ADD COLUMN IF NOT EXISTS DEPARTMENT VARCHAR(150) NULL;
ALTER TABLE USER ADD COLUMN IF NOT EXISTS OFFICE_ADDRESS VARCHAR(255) NULL;
ALTER TABLE USER ADD COLUMN IF NOT EXISTS OFFICE_HOURS VARCHAR(255) NULL;
ALTER TABLE USER ADD COLUMN IF NOT EXISTS INTERESTS_JSON TEXT NULL;
ALTER TABLE USER ADD COLUMN IF NOT EXISTS ACADEMIC_INTERESTS_JSON TEXT NULL;
ALTER TABLE USER ADD COLUMN IF NOT EXISTS NOTIFICATION_PREFERENCES_JSON TEXT NULL;
ALTER TABLE USER ADD COLUMN IF NOT EXISTS VERIFIED_ROLE TINYINT(1) DEFAULT 1;
ALTER TABLE USER ADD COLUMN IF NOT EXISTS VERIFIED_DEPARTMENT TINYINT(1) DEFAULT 0;

UPDATE USER SET ROLE = 'student' WHERE ROLE IS NULL OR ROLE = '';
UPDATE USER SET STATUS = 'approved' WHERE STATUS IS NULL OR STATUS = '';
UPDATE USER SET IS_ACTIVE = 1 WHERE IS_ACTIVE IS NULL;
UPDATE USER SET VERIFIED_ROLE = 1 WHERE VERIFIED_ROLE IS NULL;
UPDATE USER SET VERIFIED_DEPARTMENT = 0 WHERE VERIFIED_DEPARTMENT IS NULL;

-- Message and post quality-of-life columns used by the app
ALTER TABLE MESSAGE ADD COLUMN IF NOT EXISTS IS_READ TINYINT(1) DEFAULT 0;
ALTER TABLE POST ADD COLUMN IF NOT EXISTS IS_DELETED TINYINT(1) DEFAULT 0;
ALTER TABLE POST ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE TOPIC ADD COLUMN IF NOT EXISTS COVER_IMAGE_PATH VARCHAR(500) NULL;

CREATE INDEX IF NOT EXISTS idx_parent_post ON POST(PARENT_POST_ID);
CREATE UNIQUE INDEX IF NOT EXISTS unique_vote ON UPVOTE(USER_ID, POST_ID);

-- Topic request workflow support
CREATE TABLE IF NOT EXISTS TOPIC_REQUEST_META (
    TOPIC_ID INT PRIMARY KEY,
    PROOF_TEXT TEXT NULL,
    ADMIN_FEEDBACK TEXT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_topic_request_meta_topic FOREIGN KEY (TOPIC_ID) REFERENCES TOPIC(TOPIC_ID)
);

CREATE TABLE IF NOT EXISTS TOPIC_REQUEST_TIMELINE (
    TIMELINE_ID INT AUTO_INCREMENT PRIMARY KEY,
    TOPIC_ID INT NOT NULL,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    EVENT_MESSAGE TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_topic_request_timeline_topic FOREIGN KEY (TOPIC_ID) REFERENCES TOPIC(TOPIC_ID)
);

-- Reports and admin activity
CREATE TABLE IF NOT EXISTS CONTENT_REPORT (
    REPORT_ID INT AUTO_INCREMENT PRIMARY KEY,
    REPORTER_ID INT NOT NULL,
    TARGET_TYPE VARCHAR(20) NOT NULL,
    TARGET_ID INT NOT NULL,
    REASON VARCHAR(255) NOT NULL,
    DETAILS TEXT NULL,
    STATUS VARCHAR(20) DEFAULT 'pending',
    REVIEW_NOTES TEXT NULL,
    ASSIGNED_ADMIN_ID INT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REVIEWED_AT TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT fk_content_report_reporter FOREIGN KEY (REPORTER_ID) REFERENCES USER(USER_ID),
    CONSTRAINT fk_content_report_assigned_admin FOREIGN KEY (ASSIGNED_ADMIN_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE IF NOT EXISTS ADMIN_ACTIVITY_LOG (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    ADMIN_USER_ID INT NULL,
    ACTION_TYPE VARCHAR(50) NOT NULL,
    TARGET_TYPE VARCHAR(30) NOT NULL,
    TARGET_ID INT NULL,
    DESCRIPTION TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_admin_activity_log_admin FOREIGN KEY (ADMIN_USER_ID) REFERENCES USER(USER_ID)
);

-- Classes
CREATE TABLE IF NOT EXISTS CLASSROOM (
    CLASS_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLASS_CODE VARCHAR(50) NOT NULL,
    SUBJECT_NAME VARCHAR(255) NOT NULL,
    TIMINGS VARCHAR(100) NOT NULL,
    CLASS_AREA VARCHAR(255) NOT NULL,
    DEPARTMENT VARCHAR(150) NULL,
    INSTRUCTOR_ID INT NOT NULL,
    SEMESTER VARCHAR(100) NULL,
    DESCRIPTION TEXT NULL,
    DAYS VARCHAR(255) NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_classroom_instructor FOREIGN KEY (INSTRUCTOR_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE IF NOT EXISTS CLASS_ENROLLMENT (
    ENROLLMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLASS_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'pending',
    REQUESTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REVIEWED_AT TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT fk_class_enrollment_class FOREIGN KEY (CLASS_ID) REFERENCES CLASSROOM(CLASS_ID),
    CONSTRAINT fk_class_enrollment_student FOREIGN KEY (STUDENT_ID) REFERENCES USER(USER_ID),
    CONSTRAINT uq_class_enrollment UNIQUE (CLASS_ID, STUDENT_ID)
);

CREATE TABLE IF NOT EXISTS CLASS_DISCUSSION (
    DISCUSSION_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLASS_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATED_BY INT NOT NULL,
    IS_PINNED TINYINT(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_class_discussion_class FOREIGN KEY (CLASS_ID) REFERENCES CLASSROOM(CLASS_ID),
    CONSTRAINT fk_class_discussion_user FOREIGN KEY (CREATED_BY) REFERENCES USER(USER_ID)
);

CREATE TABLE IF NOT EXISTS CLASS_DISCUSSION_REPLY (
    REPLY_ID INT AUTO_INCREMENT PRIMARY KEY,
    DISCUSSION_ID INT NOT NULL,
    CLASS_ID INT NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATED_BY INT NOT NULL,
    IS_DELETED TINYINT(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_class_discussion_reply_discussion FOREIGN KEY (DISCUSSION_ID) REFERENCES CLASS_DISCUSSION(DISCUSSION_ID),
    CONSTRAINT fk_class_discussion_reply_class FOREIGN KEY (CLASS_ID) REFERENCES CLASSROOM(CLASS_ID),
    CONSTRAINT fk_class_discussion_reply_user FOREIGN KEY (CREATED_BY) REFERENCES USER(USER_ID)
);

CREATE TABLE IF NOT EXISTS CLASS_DISCUSSION_VOTE (
    VOTE_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    DISCUSSION_ID INT NULL,
    REPLY_ID INT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_class_discussion_vote_user FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    CONSTRAINT fk_class_discussion_vote_discussion FOREIGN KEY (DISCUSSION_ID) REFERENCES CLASS_DISCUSSION(DISCUSSION_ID),
    CONSTRAINT fk_class_discussion_vote_reply FOREIGN KEY (REPLY_ID) REFERENCES CLASS_DISCUSSION_REPLY(REPLY_ID)
);

CREATE TABLE IF NOT EXISTS CLASS_RESOURCE (
    RESOURCE_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLASS_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NULL,
    RESOURCE_TYPE VARCHAR(30) NOT NULL DEFAULT 'material',
    RESOURCE_URL TEXT NULL,
    FILE_PATH VARCHAR(500) NULL,
    IS_PINNED TINYINT(1) DEFAULT 0,
    CREATED_BY INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_class_resource_class FOREIGN KEY (CLASS_ID) REFERENCES CLASSROOM(CLASS_ID),
    CONSTRAINT fk_class_resource_user FOREIGN KEY (CREATED_BY) REFERENCES USER(USER_ID)
);

CREATE INDEX IF NOT EXISTS idx_class_enrollment_status ON CLASS_ENROLLMENT(CLASS_ID, STATUS);
CREATE INDEX IF NOT EXISTS idx_class_discussion_class ON CLASS_DISCUSSION(CLASS_ID, CREATED_AT);
CREATE INDEX IF NOT EXISTS idx_class_reply_discussion ON CLASS_DISCUSSION_REPLY(DISCUSSION_ID, CREATED_AT);
CREATE INDEX IF NOT EXISTS idx_content_report_status ON CONTENT_REPORT(STATUS, CREATED_AT);

